name: json-linting

on:
  push:
    branches:
      - 'master'
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: jsonlint
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSON: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
